version: "3"
services:
  back-app:
    #1.镜像来源：根据指定镜像启动(二选一)
    image: 25.30.9.228:5000/back-app:v1.1.0
    #2.镜像来源：根据指定的Dockerfile所在目录来启动(二选一)
    build: /home/start-entry/back-app(绝对路径)
    build: ./back-app (相对当前目录路径)
    #若同时配置了image和build，那么将通过build创建一个 名为image配置的镜像


    #自定义启动后的镜像名称
    container-name: back-app-container
    #宿主机目录与容器目录映射
    volumes:
      #1.宿主机绝对路径目录:容器中绝对路径目录
      - /home/back-app/logs:/home/logs
      #2.默认在容器内部创建一个数据卷，指向宿主机匿名位置[不推荐]
      - /home/logs
    #执行时，重启当前服务
    restart: always
    #启动映射端口：外部:内部
    ports:
      - "8181:8181"
    #将主机名写入到容器中的hosts文件
    extra_hosts:
      - "master:192.168.1.1"
      - "node1:192.168.1.2"
      - "node2:192.168.1.3"
        #当前镜像启动之前，必须等待以下服务启动完毕之后才能启动
        #depends_on:
        - mysql
        - kafka

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
  kafka:
    build: /home/start-entry/kafka
    ports:
      - "8787:8787"